# Change these first
owner: TwenixPlatform # Your GitHub organization or username, where this repository lives
repo: twenix-status # The name of this repository

sites:
  - name: Twenix Portal
    url: https://www.twenix.com
  - name: Twenix Students
    url: https://platform.twenix.com
  - name: Twenix Teachers
    url: https://teacher.twenix.com
  - name: Twenix Backend
    url: https://platform-back.twenix.com/alive 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.twenix.com
  #baseUrl: /twenix-status
  logoUrl: https://raw.githubusercontent.com/twenixplatform/twenix-status/master/assets/twenixlogo.svg
  name: Status Page
  introTitle: "**Twenix** status page"
  introMessage: This is the Twenix´s status page. Social media [**Twitter**](https://twitter.com/twenix)
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
